Repository KAYITARES/alight-rwanda-bn, pull requests merged in 2023-12, with the labels that each got.

#1 connectserver
  .babelrc
  .gitignore
  package.json
  src/server.js
Labels: Ready tot merge

#4 Create user api
  package.json
  src/controller/usercontroller.js
  src/middlewares/datachecker.js
  src/middlewares/validator.js
  src/middlewares/verifyaccess.js
  src/model/user.js
  src/routes/index.js
  src/routes/userroutes.js
Labels: pending, Ready tot merge

#5 job
  src/controller/jobController.js
  src/middleware/dataCheque.js
  src/middleware/validator.js
  src/middleware/verifyAccess.js
  src/model/job.js
  src/routes/index.js
  src/routes/jobRoutes.js
Labels: pending

#7 programs crud
  src/controller/programcontroller.js
  src/model/program.js
  src/routes/index.js
  src/routes/programroutes.js
Labels: pending

#9 apply verify access
  src/middlewares/validator.js
  src/routes/userroutes.js
Labels: Ready tot merge

#10 apply verify access on programs
  src/routes/programroutes.js
Labels: Ready tot merge

#11 testimonial
  src/controller/testimonialcontroller.js
  src/model/testimonial.js
  src/routes/index.js
  src/routes/testimonialroutes.js
Labels: Ready tot merge

#8 Ft jobs
  src/controller/jobController.js
  src/model/job.js
  src/model/user.js
  src/routes/index.js
  src/routes/jobRoutes.js
Labels: pending, Ready tot merge

#12 stock api
  src/controller/stockcontroller.js
  src/model/stock.js
  src/routes/index.js
  src/routes/stockroutes.js
Labels: Ready tot merge

#14 Ft jobs
  src/model/job.js
  src/routes/jobRoutes.js
Labels: Ready tot merge

#15 SendEmail Notification
  package.json
  src/controller/jobController.js
  src/controller/programcontroller.js
  src/controller/stockcontroller.js
  src/controller/testimonialcontroller.js
  src/controller/usercontroller.js
  src/routes/index.js
  src/utils/email.js
  src/utils/programemail.js
  src/utils/stockemail.js
  src/utils/testimonialemail.js
Labels: Ready tot merge
